import { writeFileSync } from "fs";

// Generates fabricated fiber network GeoJSON for Appleton, WI.
// Run: node scripts/generateNetwork.mjs

const BOUNDS = {
  minLat: 44.24347867098507,
  maxLat: 44.287487251442116,
  minLng: -88.43729415893554,
  maxLng: -88.35300842285156,
};

// E-W corridors (latitudes)
const LAT = {
  farSouth: 44.244,
  southB: 44.248,
  southA: 44.252,
  wiscon: 44.258,
  collegeS: 44.262,
  college: 44.2634,
  collegeN: 44.266,
  midN: 44.27,
  northland: 44.275,
  northB: 44.28,
  farNorth: 44.287,
};

// N-S corridors (longitudes)
const LNG = {
  farWest: -88.436,
  westC: -88.432,
  westB: -88.43,
  westA: -88.426,
  memorial: -88.4154,
  centralB: -88.408,
  oneida: -88.4011,
  centralA: -88.396,
  ballard: -88.39,
  midE: -88.382,
  hwy41: -88.37,
  eastA: -88.363,
  farEast: -88.356,
};

const nodes = [
  {
    id: "A01",
    type: "manhole",
    status: "planned",
    lat: LAT.farSouth,
    lng: LNG.farWest,
  },
  {
    id: "A02",
    type: "splice",
    status: "planned",
    lat: LAT.farSouth,
    lng: LNG.westA,
  },
  {
    id: "A03",
    type: "cabinet",
    status: "active",
    lat: LAT.farSouth,
    lng: LNG.memorial,
  },
  {
    id: "A04",
    type: "splice",
    status: "active",
    lat: LAT.farSouth,
    lng: LNG.oneida,
  },
  {
    id: "A05",
    type: "cabinet",
    status: "active",
    lat: LAT.farSouth,
    lng: LNG.ballard,
  },
  {
    id: "A06",
    type: "splice",
    status: "active",
    lat: LAT.farSouth,
    lng: LNG.hwy41,
  },
  {
    id: "A07",
    type: "manhole",
    status: "planned",
    lat: LAT.farSouth,
    lng: LNG.farEast,
  },

  {
    id: "B01",
    type: "splice",
    status: "active",
    lat: LAT.southB,
    lng: LNG.farWest,
  },
  {
    id: "B02",
    type: "cabinet",
    status: "active",
    lat: LAT.southB,
    lng: LNG.westB,
  },
  {
    id: "B03",
    type: "splice",
    status: "outage",
    lat: LAT.southB,
    lng: LNG.westA,
  },
  {
    id: "B04",
    type: "cabinet",
    status: "outage",
    lat: LAT.southB,
    lng: LNG.memorial,
  },
  {
    id: "B05",
    type: "splice",
    status: "active",
    lat: LAT.southB,
    lng: LNG.centralB,
  },
  {
    id: "B06",
    type: "cabinet",
    status: "active",
    lat: LAT.southB,
    lng: LNG.oneida,
  },
  {
    id: "B07",
    type: "splice",
    status: "active",
    lat: LAT.southB,
    lng: LNG.ballard,
  },
  {
    id: "B08",
    type: "manhole",
    status: "active",
    lat: LAT.southB,
    lng: LNG.midE,
  },
  {
    id: "B09",
    type: "cabinet",
    status: "active",
    lat: LAT.southB,
    lng: LNG.hwy41,
  },
  {
    id: "B10",
    type: "splice",
    status: "planned",
    lat: LAT.southB,
    lng: LNG.farEast,
  },

  {
    id: "C01",
    type: "splice",
    status: "active",
    lat: LAT.southA,
    lng: LNG.farWest,
  },
  {
    id: "C02",
    type: "manhole",
    status: "active",
    lat: LAT.southA,
    lng: LNG.memorial,
  },
  {
    id: "C03",
    type: "splice",
    status: "active",
    lat: LAT.southA,
    lng: LNG.oneida,
  },
  {
    id: "C04",
    type: "cabinet",
    status: "active",
    lat: LAT.southA,
    lng: LNG.hwy41,
  },
  {
    id: "C05",
    type: "splice",
    status: "planned",
    lat: LAT.southA,
    lng: LNG.farEast,
  },

  {
    id: "D01",
    type: "splice",
    status: "active",
    lat: LAT.wiscon,
    lng: LNG.farWest,
  },
  {
    id: "D02",
    type: "cabinet",
    status: "active",
    lat: LAT.wiscon,
    lng: LNG.westB,
  },
  {
    id: "D03",
    type: "splice",
    status: "active",
    lat: LAT.wiscon,
    lng: LNG.westA,
  },
  {
    id: "D04",
    type: "manhole",
    status: "active",
    lat: LAT.wiscon,
    lng: LNG.memorial,
  },
  {
    id: "D05",
    type: "splice",
    status: "active",
    lat: LAT.wiscon,
    lng: LNG.centralB,
  },
  {
    id: "D06",
    type: "cabinet",
    status: "active",
    lat: LAT.wiscon,
    lng: LNG.oneida,
  },
  {
    id: "D07",
    type: "splice",
    status: "active",
    lat: LAT.wiscon,
    lng: LNG.ballard,
  },
  {
    id: "D08",
    type: "manhole",
    status: "active",
    lat: LAT.wiscon,
    lng: LNG.midE,
  },
  { id: "D09", type: "pop", status: "active", lat: LAT.wiscon, lng: LNG.hwy41 },
  {
    id: "D10",
    type: "splice",
    status: "active",
    lat: LAT.wiscon,
    lng: LNG.eastA,
  },
  {
    id: "D11",
    type: "cabinet",
    status: "active",
    lat: LAT.wiscon,
    lng: LNG.farEast,
  },

  {
    id: "E01",
    type: "pop",
    status: "active",
    lat: LAT.college,
    lng: LNG.farWest,
  },
  {
    id: "E02",
    type: "splice",
    status: "active",
    lat: LAT.college,
    lng: LNG.westB,
  },
  {
    id: "E03",
    type: "cabinet",
    status: "active",
    lat: LAT.college,
    lng: LNG.westA,
  },
  {
    id: "E04",
    type: "pop",
    status: "active",
    lat: LAT.college,
    lng: LNG.memorial,
  },
  {
    id: "E05",
    type: "splice",
    status: "active",
    lat: LAT.college,
    lng: LNG.centralB,
  },
  {
    id: "E06",
    type: "cabinet",
    status: "active",
    lat: LAT.college,
    lng: LNG.oneida,
  },
  {
    id: "E07",
    type: "splice",
    status: "planned",
    lat: LAT.college,
    lng: LNG.ballard,
  },
  {
    id: "E08",
    type: "manhole",
    status: "planned",
    lat: LAT.college,
    lng: LNG.midE,
  },
  {
    id: "E09",
    type: "cabinet",
    status: "active",
    lat: LAT.college,
    lng: LNG.hwy41,
  },
  {
    id: "E10",
    type: "splice",
    status: "planned",
    lat: LAT.college,
    lng: LNG.eastA,
  },
  {
    id: "E11",
    type: "cabinet",
    status: "planned",
    lat: LAT.college,
    lng: LNG.farEast,
  },

  {
    id: "F01",
    type: "splice",
    status: "planned",
    lat: LAT.northland,
    lng: LNG.farWest,
  },
  {
    id: "F02",
    type: "cabinet",
    status: "planned",
    lat: LAT.northland,
    lng: LNG.westA,
  },
  {
    id: "F03",
    type: "splice",
    status: "active",
    lat: LAT.northland,
    lng: LNG.memorial,
  },
  {
    id: "F04",
    type: "cabinet",
    status: "active",
    lat: LAT.northland,
    lng: LNG.centralB,
  },
  {
    id: "F05",
    type: "splice",
    status: "planned",
    lat: LAT.northland,
    lng: LNG.oneida,
  },
  {
    id: "F06",
    type: "cabinet",
    status: "planned",
    lat: LAT.northland,
    lng: LNG.ballard,
  },
  {
    id: "F07",
    type: "manhole",
    status: "planned",
    lat: LAT.northland,
    lng: LNG.midE,
  },
  {
    id: "F08",
    type: "splice",
    status: "planned",
    lat: LAT.northland,
    lng: LNG.hwy41,
  },
  {
    id: "F09",
    type: "cabinet",
    status: "planned",
    lat: LAT.northland,
    lng: LNG.farEast,
  },

  {
    id: "G01",
    type: "pop",
    status: "active",
    lat: LAT.farNorth,
    lng: LNG.memorial,
  },
  {
    id: "G02",
    type: "splice",
    status: "active",
    lat: LAT.farNorth,
    lng: LNG.centralB,
  },
  {
    id: "G03",
    type: "cabinet",
    status: "planned",
    lat: LAT.farNorth,
    lng: LNG.oneida,
  },
  {
    id: "G04",
    type: "splice",
    status: "planned",
    lat: LAT.farNorth,
    lng: LNG.ballard,
  },
  {
    id: "G05",
    type: "manhole",
    status: "planned",
    lat: LAT.farNorth,
    lng: LNG.hwy41,
  },

  {
    id: "G_WA",
    type: "splice",
    status: "planned",
    lat: LAT.farNorth,
    lng: LNG.westA,
  },
  {
    id: "G_WB",
    type: "cabinet",
    status: "planned",
    lat: LAT.farNorth,
    lng: LNG.westB,
  },
  {
    id: "G_WC",
    type: "splice",
    status: "planned",
    lat: LAT.farNorth,
    lng: LNG.westC,
  },
  {
    id: "G_FW",
    type: "pop",
    status: "planned",
    lat: LAT.farNorth,
    lng: LNG.farWest,
  },

  {
    id: "I_FW",
    type: "cabinet",
    status: "planned",
    lat: 44.28,
    lng: LNG.farWest,
  },
  { id: "I_WC", type: "splice", status: "planned", lat: 44.28, lng: LNG.westC },
  {
    id: "I_WB",
    type: "manhole",
    status: "planned",
    lat: 44.28,
    lng: LNG.westB,
  },
  { id: "I_WA", type: "splice", status: "planned", lat: 44.28, lng: LNG.westA },
  {
    id: "I_MEM",
    type: "cabinet",
    status: "active",
    lat: 44.28,
    lng: LNG.memorial,
  },
  {
    id: "I_CB",
    type: "splice",
    status: "active",
    lat: 44.28,
    lng: LNG.centralB,
  },

  {
    id: "H_FW",
    type: "splice",
    status: "planned",
    lat: 44.27,
    lng: LNG.farWest,
  },
  {
    id: "H_WC",
    type: "cabinet",
    status: "planned",
    lat: 44.27,
    lng: LNG.westC,
  },
  { id: "H_WB", type: "splice", status: "planned", lat: 44.27, lng: LNG.westB },
  {
    id: "H_WA",
    type: "manhole",
    status: "planned",
    lat: 44.27,
    lng: LNG.westA,
  },
  {
    id: "H_MEM",
    type: "splice",
    status: "active",
    lat: 44.27,
    lng: LNG.memorial,
  },

  {
    id: "WC_A",
    type: "splice",
    status: "planned",
    lat: LAT.farSouth,
    lng: LNG.westC,
  },
  {
    id: "WC_B",
    type: "cabinet",
    status: "active",
    lat: LAT.southB,
    lng: LNG.westC,
  },
  {
    id: "WC_C",
    type: "splice",
    status: "active",
    lat: LAT.southA,
    lng: LNG.westC,
  },
  {
    id: "WC_D",
    type: "manhole",
    status: "active",
    lat: LAT.wiscon,
    lng: LNG.westC,
  },
  {
    id: "WC_E",
    type: "splice",
    status: "active",
    lat: LAT.college,
    lng: LNG.westC,
  },
  {
    id: "WC_F",
    type: "cabinet",
    status: "planned",
    lat: LAT.northland,
    lng: LNG.westC,
  },

  {
    id: "WB_F",
    type: "splice",
    status: "planned",
    lat: LAT.northland,
    lng: LNG.westB,
  },
];

const routesDefs = [
  {
    id: "S_A01",
    from: "A01",
    to: "A02",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_A02",
    from: "A02",
    to: "A03",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_A03",
    from: "A03",
    to: "A04",
    status: "active",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_A04",
    from: "A04",
    to: "A05",
    status: "active",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_A05",
    from: "A05",
    to: "A06",
    status: "active",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_A06",
    from: "A06",
    to: "A07",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },

  {
    id: "S_B01",
    from: "B01",
    to: "B02",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_B02",
    from: "B02",
    to: "B03",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_B03",
    from: "B03",
    to: "B04",
    status: "outage",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_B04",
    from: "B04",
    to: "B05",
    status: "outage",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_B05",
    from: "B05",
    to: "B06",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_B06",
    from: "B06",
    to: "B07",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_B07",
    from: "B07",
    to: "B08",
    status: "active",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_B08",
    from: "B08",
    to: "B09",
    status: "active",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_B09",
    from: "B09",
    to: "B10",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },

  {
    id: "S_C01",
    from: "C01",
    to: "C02",
    status: "active",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_C02",
    from: "C02",
    to: "C03",
    status: "active",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_C03",
    from: "C03",
    to: "C04",
    status: "active",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_C04",
    from: "C04",
    to: "C05",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },

  {
    id: "S_D01",
    from: "D01",
    to: "D02",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_D02",
    from: "D02",
    to: "D03",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_D03",
    from: "D03",
    to: "D04",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_D04",
    from: "D04",
    to: "D05",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_D05",
    from: "D05",
    to: "D06",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_D06",
    from: "D06",
    to: "D07",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_D07",
    from: "D07",
    to: "D08",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_D08",
    from: "D08",
    to: "D09",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_D09",
    from: "D09",
    to: "D10",
    status: "active",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_D10",
    from: "D10",
    to: "D11",
    status: "active",
    type: "distribution",
    capacity: "24F",
  },

  {
    id: "S_E01",
    from: "E01",
    to: "E02",
    status: "active",
    type: "backbone",
    capacity: "96F",
  },
  {
    id: "S_E02",
    from: "E02",
    to: "E03",
    status: "active",
    type: "backbone",
    capacity: "96F",
  },
  {
    id: "S_E03",
    from: "E03",
    to: "E04",
    status: "active",
    type: "backbone",
    capacity: "96F",
  },
  {
    id: "S_E04",
    from: "E04",
    to: "E05",
    status: "active",
    type: "backbone",
    capacity: "96F",
  },
  {
    id: "S_E05",
    from: "E05",
    to: "E06",
    status: "active",
    type: "backbone",
    capacity: "96F",
  },
  {
    id: "S_E06",
    from: "E06",
    to: "E07",
    status: "planned",
    type: "backbone",
    capacity: "96F",
  },
  {
    id: "S_E07",
    from: "E07",
    to: "E08",
    status: "planned",
    type: "backbone",
    capacity: "48F",
  },
  {
    id: "S_E08",
    from: "E08",
    to: "E09",
    status: "planned",
    type: "backbone",
    capacity: "48F",
  },
  {
    id: "S_E09",
    from: "E09",
    to: "E10",
    status: "planned",
    type: "backbone",
    capacity: "48F",
  },
  {
    id: "S_E10",
    from: "E10",
    to: "E11",
    status: "planned",
    type: "backbone",
    capacity: "48F",
  },

  {
    id: "S_F01",
    from: "F01",
    to: "F02",
    status: "planned",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_F02",
    from: "F02",
    to: "F03",
    status: "planned",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_F03",
    from: "F03",
    to: "F04",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_F04",
    from: "F04",
    to: "F05",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_F05",
    from: "F05",
    to: "F06",
    status: "planned",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_F06",
    from: "F06",
    to: "F07",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_F07",
    from: "F07",
    to: "F08",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_F08",
    from: "F08",
    to: "F09",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },

  {
    id: "S_G01",
    from: "G01",
    to: "G02",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_G02",
    from: "G02",
    to: "G03",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_G03",
    from: "G03",
    to: "G04",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_G04",
    from: "G04",
    to: "G05",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },

  {
    id: "S_V01",
    from: "A01",
    to: "B01",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_V02",
    from: "B01",
    to: "C01",
    status: "active",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_V03",
    from: "C01",
    to: "D01",
    status: "active",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_V04",
    from: "D01",
    to: "E01",
    status: "active",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_V05",
    from: "E01",
    to: "F01",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },

  {
    id: "S_V10",
    from: "A03",
    to: "B04",
    status: "active",
    type: "backbone",
    capacity: "96F",
  },
  {
    id: "S_V11",
    from: "B04",
    to: "C02",
    status: "outage",
    type: "backbone",
    capacity: "96F",
  },
  {
    id: "S_V12",
    from: "C02",
    to: "D04",
    status: "active",
    type: "backbone",
    capacity: "96F",
  },
  {
    id: "S_V13",
    from: "D04",
    to: "E04",
    status: "active",
    type: "backbone",
    capacity: "96F",
  },

  {
    id: "S_V20",
    from: "A04",
    to: "B06",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_V21",
    from: "B06",
    to: "C03",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_V22",
    from: "C03",
    to: "D06",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_V23",
    from: "D06",
    to: "E06",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_V24",
    from: "E06",
    to: "F05",
    status: "planned",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_V25",
    from: "F05",
    to: "G03",
    status: "planned",
    type: "distribution",
    capacity: "48F",
  },

  {
    id: "S_V30",
    from: "A05",
    to: "B07",
    status: "active",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_V31",
    from: "B07",
    to: "D07",
    status: "active",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_V32",
    from: "D07",
    to: "E07",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_V33",
    from: "E07",
    to: "F06",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_V34",
    from: "F06",
    to: "G04",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },

  {
    id: "S_V40",
    from: "A06",
    to: "B09",
    status: "active",
    type: "backbone",
    capacity: "96F",
  },
  {
    id: "S_V41",
    from: "B09",
    to: "C04",
    status: "active",
    type: "backbone",
    capacity: "96F",
  },
  {
    id: "S_V42",
    from: "C04",
    to: "D09",
    status: "active",
    type: "backbone",
    capacity: "96F",
  },
  {
    id: "S_V43",
    from: "D09",
    to: "E09",
    status: "active",
    type: "backbone",
    capacity: "96F",
  },
  {
    id: "S_V44",
    from: "E09",
    to: "F08",
    status: "planned",
    type: "backbone",
    capacity: "96F",
  },
  {
    id: "S_V45",
    from: "F08",
    to: "G05",
    status: "planned",
    type: "backbone",
    capacity: "96F",
  },

  {
    id: "S_GW1",
    from: "G_FW",
    to: "G_WC",
    status: "planned",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_GW2",
    from: "G_WC",
    to: "G_WB",
    status: "planned",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_GW3",
    from: "G_WB",
    to: "G_WA",
    status: "planned",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_GW4",
    from: "G_WA",
    to: "G01",
    status: "planned",
    type: "distribution",
    capacity: "48F",
  },

  {
    id: "S_IW1",
    from: "I_FW",
    to: "I_WC",
    status: "planned",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_IW2",
    from: "I_WC",
    to: "I_WB",
    status: "planned",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_IW3",
    from: "I_WB",
    to: "I_WA",
    status: "planned",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_IW4",
    from: "I_WA",
    to: "I_MEM",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_IW5",
    from: "I_MEM",
    to: "I_CB",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },

  {
    id: "S_HW1",
    from: "H_FW",
    to: "H_WC",
    status: "planned",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_HW2",
    from: "H_WC",
    to: "H_WB",
    status: "planned",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_HW3",
    from: "H_WB",
    to: "H_WA",
    status: "planned",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_HW4",
    from: "H_WA",
    to: "H_MEM",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },

  {
    id: "S_WCV1",
    from: "WC_A",
    to: "WC_B",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_WCV2",
    from: "WC_B",
    to: "WC_C",
    status: "active",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_WCV3",
    from: "WC_C",
    to: "WC_D",
    status: "active",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_WCV4",
    from: "WC_D",
    to: "WC_E",
    status: "active",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_WCV5",
    from: "WC_E",
    to: "WC_F",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_WCV6",
    from: "WC_F",
    to: "H_WC",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_WCV7",
    from: "H_WC",
    to: "I_WC",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_WCV8",
    from: "I_WC",
    to: "G_WC",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },

  {
    id: "S_WCH1",
    from: "A01",
    to: "WC_A",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_WCH2",
    from: "B01",
    to: "WC_B",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_WCH3",
    from: "C01",
    to: "WC_C",
    status: "active",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_WCH4",
    from: "D01",
    to: "WC_D",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_WCH5",
    from: "E01",
    to: "WC_E",
    status: "active",
    type: "backbone",
    capacity: "96F",
  },
  {
    id: "S_WCH6",
    from: "F01",
    to: "WC_F",
    status: "planned",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_WCH7",
    from: "H_FW",
    to: "H_WC",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_WCH8",
    from: "I_FW",
    to: "I_WC",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_WCH9",
    from: "G_FW",
    to: "G_WC",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },

  {
    id: "S_FWN1",
    from: "F01",
    to: "H_FW",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_FWN2",
    from: "H_FW",
    to: "I_FW",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_FWN3",
    from: "I_FW",
    to: "G_FW",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },

  {
    id: "S_WBN1",
    from: "E02",
    to: "WB_F",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_WBN2",
    from: "WB_F",
    to: "H_WB",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_WBN3",
    from: "H_WB",
    to: "I_WB",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_WBN4",
    from: "I_WB",
    to: "G_WB",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },

  {
    id: "S_WAN1",
    from: "F02",
    to: "H_WA",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_WAN2",
    from: "H_WA",
    to: "I_WA",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_WAN3",
    from: "I_WA",
    to: "G_WA",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },

  {
    id: "S_MN1",
    from: "E04",
    to: "H_MEM",
    status: "active",
    type: "backbone",
    capacity: "96F",
  },
  {
    id: "S_MN2",
    from: "H_MEM",
    to: "F03",
    status: "active",
    type: "backbone",
    capacity: "96F",
  },
  {
    id: "S_MN3",
    from: "F03",
    to: "I_MEM",
    status: "active",
    type: "backbone",
    capacity: "96F",
  },
  {
    id: "S_MN4",
    from: "I_MEM",
    to: "G01",
    status: "active",
    type: "backbone",
    capacity: "96F",
  },

  {
    id: "S_CBN1",
    from: "F04",
    to: "I_CB",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },
  {
    id: "S_CBN2",
    from: "I_CB",
    to: "G02",
    status: "active",
    type: "distribution",
    capacity: "48F",
  },

  {
    id: "S_V50",
    from: "A07",
    to: "B10",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_V51",
    from: "B10",
    to: "C05",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_V52",
    from: "C05",
    to: "D11",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_V53",
    from: "D11",
    to: "E11",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
  {
    id: "S_V54",
    from: "E11",
    to: "F09",
    status: "planned",
    type: "distribution",
    capacity: "24F",
  },
];

const nodeMap = Object.fromEntries(nodes.map((n) => [n.id, n]));

for (const s of routesDefs) {
  if (!nodeMap[s.from])
    throw new Error(`Segment ${s.id} references unknown node ${s.from}`);
  if (!nodeMap[s.to])
    throw new Error(`Segment ${s.id} references unknown node ${s.to}`);
}

for (const n of nodes) {
  if (
    n.lat < BOUNDS.minLat ||
    n.lat > BOUNDS.maxLat ||
    n.lng < BOUNDS.minLng ||
    n.lng > BOUNDS.maxLng
  ) {
    console.warn(`Node ${n.id} outside bounds: lat=${n.lat}, lng=${n.lng}`);
  }
}

const routess = {
  type: "FeatureCollection",
  features: routesDefs.map((s) => {
    const a = nodeMap[s.from];
    const b = nodeMap[s.to];
    return {
      type: "Feature",
      geometry: {
        type: "LineString",
        coordinates: [
          [a.lng, a.lat],
          [b.lng, b.lat],
        ],
      },
      properties: {
        id: s.id,
        status: s.status,
        type: s.type,
        capacity: s.capacity,
        fromNode: s.from,
        toNode: s.to,
      },
    };
  }),
};

const networkNodes = {
  type: "FeatureCollection",
  features: nodes.map((n) => ({
    type: "Feature",
    geometry: { type: "Point", coordinates: [n.lng, n.lat] },
    properties: { id: n.id, type: n.type, status: n.status },
  })),
};

writeFileSync("public/data/fiberRoutes.json", JSON.stringify(routess));
writeFileSync("public/data/fiberNodes.json", JSON.stringify(networkNodes));
console.log(
  `Written ${routess.features.length} routess and ${networkNodes.features.length} nodes.`,
);
